name: ultralitedb
description: Port of C# UltraLiteDB to Dart for usage in Flutter projects.
version: 0.0.1
repository: https://github.com/softak098/ultralitedb_dart.git
  
environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
 
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
