name: ultralitedb_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^13.0.0
  build: ^4.0.6
  source_gen: ^4.2.3
  
  ultralitedb:
    path: ../ultralitedb

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.15.0
